### ISSUE TITLE
IndexError: index 4 is out of bounds for axis 0 with size 4

### ISSUE THREAD

**Issue by EChenevert** [GeostatsGuy/GeostatsPy#38]
I am trying to implement the declustering function on my dataframe which consists of longitude, latitude, and sediment accumulation variables, but I am getting an out of index error. I am having trouble fixing this error myself, could someone help me figure this out? Below is the traceback:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\etachen\AppData\Local\JetBrains\PyCharm 2021.2.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\etachen\AppData\Local\JetBrains\PyCharm 2021.2.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/etachen/PycharmProjects/ai_algo_tests/declustering_medium_test.py", line 21, in <module>
    W, Csize, Dmean = geostat.declus(df,'Longitude', 'Latitude', 'Average Accretion (mm)',
  File "C:\Users\etachen\Anaconda3\envs\ai_algo_tests\lib\site-packages\geostatspy\geostats.py", line 1607, in declus
    cellwt[icell] = cellwt[icell] + 1.0
IndexError: index 4 is out of bounds for axis 0 with size 4

**Comment by jonm3D** [comment]
I am also getting this error, but changing noff doesn't fix the issue for me. I'm using a geodataframe with dimension (515,20) and the following DECLUS inputs:

weights, cell_sizes, dmeans = geostats.declus(ddf,'X','Y','dZ',
                                          iminmax = 1, 
                                          noff= 5, ncell=1000,
                                          cmin=1, cmax=50)

The problematic dataframe can be downloaded [here (link to download gpkg from box)](https://utexas.box.com/s/iyagicnel51mjjmuo2m2kvzadte2gjjc).

I've tried resetting the dataframe index, using a different subset of rows/columns, converting to a standard Dataframe, varying the values for iminmax/noff/ncell/cmin/cmax but I haven't been able to isolate the cause.

Here is the specific error message I am getting:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In [30], line 9
      6 # number of cell sizes to iterate through, if taking too long, decrease this
      7 ncell = 1000
----> 9 weights, cell_sizes, dmeans = geostats.declus(ddf.loc[:, ['X', 'Y', 'dZ']],'X','Y','dZ',
     10                                           iminmax = 1, 
     11                                           noff= 10, ncell=ncell,
     12                                           cmin=min_cell_size, cmax=max_cell_size)
     14 ddf['W'] = weights
     15 ddf.head()                                  

File /srv/conda/envs/notebook/lib/python3.10/site-packages/geostatspy/geostats.py:1607, in declus(df, xcol, ycol, vcol, iminmax, noff, ncell, cmin, cmax)
   1605     icell = icellx + (icelly - 1) * ncellx
   1606     index[i] = icell
-> 1607     cellwt[icell] = cellwt[icell] + 1.0
   1609 # The weight assigned to each datum is inversely proportional to the
   1610 # number of data in the cell. We first need to get the sum of
   1611 # weights so that we can normalize the weights to sum to one
   1612 sumw = 0.0

IndexError: index 3109994 is out of bounds for axis 0 with size 3109994```
